# Default values for node-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 'docker.io/mohammadimran0186/task1'
  pullPolicy: Always
  # Specify the image tag for ARM64 architecture
  tag: "latest-arm64"
  containerPort: 3000

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations:
    meta.helm.sh/release-name: "node-app"
    meta.helm.sh/release-namespace: "default"
  name: "node-app"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
